[project]
name = "sgs-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.2",
    "redis>=5.2.1",
    "starlette>=0.46.0",
    "uvicorn>=0.34.0",
]
